python:
  - 3.2
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "python -m SimpleHTTPServer"
script: phantomjs tests/lib/run-qunit.js "http://localhost:8000/tests/index.html"