rvm:
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: phantomjs tests/lib/run-qunit.js https://github.com/cerebris/ember-rest/blob/master/tests/index.html